title: OpenXR Toolkit
description: OpenXR Toolkit
remote_theme: pmarsceill/just-the-docs
baseurl: "/OpenXR-Toolkit"
url: "https://mbucchia.github.io"
github:
  owner_name: Matthieu Bucchianeri
ga_tracking: G-NLCPR2X97D

logo: "logo.png"
color_scheme: dark
heading_anchors: true
gh_edit_link: false
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  "Join the Discord server":
    - "https://discord.gg/mPKJYeGUjH"
aux_links_new_tab: true

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false